version: '3.4'

services:
  eventschedulingandregistrationdb:
         container_name: eventschedulingandregistrationdb
         environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=EventDb
         restart: always
         ports:
            - "5433:5432"
         volumes:
          - postgres_event:/var/lib/postgresql/data/
  eventschedulingandregistration.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=eventschedulingandregistrationdb;Port=5432;Database=EventDb;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "7080:8080"
      - "7081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro